services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${BACKEND_PORT:-3000}:8000"
    volumes:
      # development volume
      - ./backend:/app
    restart: unless-stopped
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT:-8080}:5173"
    volumes:
      # development volume
      - ./frontend/src:/app/src
    environment:
      - VITE_BACKEND_URL=http://localhost:${BACKEND_PORT:-3000}
    restart: unless-stopped
    depends_on:
      - backend